/*
 * Copyright By @2dgirlismywaifu (2023)
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *           http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.notelysia.bookstoremaven.Admin;

import com.notelysia.bookstoremaven.AboutSoftware;
import com.notelysia.bookstoremaven.ChangePassword.ChangePassAccount;
import com.notelysia.bookstoremaven.IconImageUtilities;
import com.notelysia.bookstoremaven.Saler.BillHistory;
import com.notelysia.bookstoremaven.Storage.BookInformation;
import com.notelysia.bookstoremaven.Storage.BookPublishers;
import com.notelysia.bookstoremaven.LoginForm;
import com.notelysia.bookstoremaven.LookandFeel;
import com.notelysia.bookstoremaven.Recovery.RecKeyAccount;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public final class AdminPageForm extends javax.swing.JFrame {    
    IconImageUtilities iconImageUtilities = new IconImageUtilities();
    private String username;

    /**
     * Creates new form Main
     */
    public AdminPageForm(String username) {
        this.username = username;
        initComponents();
        iconImageUtilities.setWindowImage(AdminPageForm.this);
        UserAdmin.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem8 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        MainMenu = new javax.swing.JMenu();
        UserAdmin = new javax.swing.JMenuItem();
        Changpassword = new javax.swing.JMenuItem();
        RecoveryKey = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenuItem();
        ExitApplication = new javax.swing.JMenuItem();
        BookInformationMenu = new javax.swing.JMenu();
        BookInformation = new javax.swing.JMenuItem();
        BookPublisher = new javax.swing.JMenuItem();
        CustomerInformation = new javax.swing.JMenuItem();
        DangerOption = new javax.swing.JCheckBoxMenuItem();
        EmployeeMenu = new javax.swing.JMenu();
        EmployeeInformation = new javax.swing.JMenuItem();
        GrantAccount = new javax.swing.JMenuItem();
        ReportMenu = new javax.swing.JMenu();
        BillHistory = new javax.swing.JMenuItem();
        DebitMonth = new javax.swing.JMenuItem();
        SalesMonth = new javax.swing.JMenuItem();
        AboutMenu = new javax.swing.JMenu();
        GroupInformation = new javax.swing.JMenuItem();

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản trị viên");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN TRỊ HỆ THỐNG");
        jLabel2.setToolTipText("");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1200px-El_Ateneo_Bookstore.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainMenu.setText("File");

        UserAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-name-16.png"))); // NOI18N
        UserAdmin.setText("Thông tin tài khoản");
        UserAdmin.setEnabled(false);
        MainMenu.add(UserAdmin);

        Changpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modify-key-icon (1).png"))); // NOI18N
        Changpassword.setText("Thay đổi mật khẩu");
        Changpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangpasswordActionPerformed(evt);
            }
        });
        MainMenu.add(Changpassword);

        RecoveryKey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modify-key-icon (1).png"))); // NOI18N
        RecoveryKey.setText("Khoá phục hồi");
        RecoveryKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecoveryKeyActionPerformed(evt);
            }
        });
        MainMenu.add(RecoveryKey);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logout-icon.png"))); // NOI18N
        Logout.setText("Đăng xuất");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        MainMenu.add(Logout);

        ExitApplication.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        ExitApplication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actions-application-exit-icon.png"))); // NOI18N
        ExitApplication.setText("Thoát");
        ExitApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitApplicationActionPerformed(evt);
            }
        });
        MainMenu.add(ExitApplication);

        jMenuBar2.add(MainMenu);

        BookInformationMenu.setText("Thông tin");

        BookInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-create-document-16.png"))); // NOI18N
        BookInformation.setText("Thông tin sách");
        BookInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookInformationActionPerformed(evt);
            }
        });
        BookInformationMenu.add(BookInformation);

        BookPublisher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-create-document-16.png"))); // NOI18N
        BookPublisher.setText("Nhà cung cấp");
        BookPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookPublisherActionPerformed(evt);
            }
        });
        BookInformationMenu.add(BookPublisher);

        CustomerInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-create-document-16.png"))); // NOI18N
        CustomerInformation.setText("Khách hàng");
        CustomerInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerInformationActionPerformed(evt);
            }
        });
        BookInformationMenu.add(CustomerInformation);

        DangerOption.setText("Cho phép xuất thông tin khách hàng");
        DangerOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangerOptionActionPerformed(evt);
            }
        });
        BookInformationMenu.add(DangerOption);

        jMenuBar2.add(BookInformationMenu);

        EmployeeMenu.setText("Nhân viên");

        EmployeeInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-create-document-16.png"))); // NOI18N
        EmployeeInformation.setText("Thông tin nhân viên");
        EmployeeInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeInformationActionPerformed(evt);
            }
        });
        EmployeeMenu.add(EmployeeInformation);

        GrantAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-create-document-16.png"))); // NOI18N
        GrantAccount.setText("Cấp tài khoản");
        GrantAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrantAccountActionPerformed(evt);
            }
        });
        EmployeeMenu.add(GrantAccount);

        jMenuBar2.add(EmployeeMenu);

        ReportMenu.setText("Báo cáo");

        BillHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-create-document-16.png"))); // NOI18N
        BillHistory.setText("Lịch sử hoá đơn");
        BillHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillHistoryActionPerformed(evt);
            }
        });
        ReportMenu.add(BillHistory);

        DebitMonth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sales-report-icon.png"))); // NOI18N
        DebitMonth.setText("Công Nợ");
        DebitMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebitMonthActionPerformed(evt);
            }
        });
        ReportMenu.add(DebitMonth);

        SalesMonth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sales-report-icon.png"))); // NOI18N
        SalesMonth.setText("Doanh Thu");
        SalesMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesMonthActionPerformed(evt);
            }
        });
        ReportMenu.add(SalesMonth);

        jMenuBar2.add(ReportMenu);

        AboutMenu.setText("Về");

        GroupInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-info-16.png"))); // NOI18N
        GroupInformation.setText("Thông tin");
        GroupInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroupInformationActionPerformed(evt);
            }
        });
        AboutMenu.add(GroupInformation);

        jMenuBar2.add(AboutMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   //thoát pm
    private void ExitApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitApplicationActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_ExitApplicationActionPerformed
//đăng xuất
    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {                                       
         // TODO add your handling code here:
         this.dispose();
         new LoginForm().main();
    }
//GEN-FIRST:event_LogoutActionPerformed

//GEN-LAST:event_LogoutActionPerformed
     //thay đổi mật khẩu
    private void ChangpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangpasswordActionPerformed
        // TODO add your handling code here:       
        new ChangePassAccount(this, UserAdmin.getText()).main();
    }
//GEN-LAST:event_ChangpasswordActionPerformed
    //khoá phục hồi
    private void RecoveryKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecoveryKeyActionPerformed
        // TODO add your handling code here:
        new RecKeyAccount(UserAdmin.getText()).main();
    }//GEN-LAST:event_RecoveryKeyActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:                    
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void GroupInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupInformationActionPerformed
        // TODO add your handling code here:        
        new AboutSoftware().main();
    }//GEN-LAST:event_GroupInformationActionPerformed
    //Thông tin khách hàng
    private void CustomerInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerInformationActionPerformed
        // TODO add your handling code here:     
        new CustomerInformation().main();
    }//GEN-LAST:event_CustomerInformationActionPerformed
    //Cấp tài khoản cho nhân viên
    private void GrantAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrantAccountActionPerformed
        // TODO add your handling code here:      
        new GrantAccountForm(username).main();
    }//GEN-LAST:event_GrantAccountActionPerformed
    //cho phep xuat thong tin khach hang
    private void DangerOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangerOptionActionPerformed
        // TODO add your handling code here:
        
        if (DangerOption.isSelected()){
            int asking0 = JOptionPane.showConfirmDialog(null, "Cho phép xuất thông tin khách hàng?\nĐây là dữ liệu nhạy cảm\n"
                    + "Kích hoạt đồng nghĩa chịu trách nhiệm nếu làm để lộ thông tin\nVẫn tiếp tục kích hoạt?",
                    "Cảnh báo",JOptionPane.YES_NO_OPTION,JOptionPane.ERROR_MESSAGE);
            if (asking0 == JOptionPane.YES_OPTION ) {               
                JOptionPane.showMessageDialog(null, "Kích hoạt thành công","Cảnh báo",JOptionPane.ERROR_MESSAGE);               
            } else if (asking0 == JOptionPane.NO_OPTION){
                this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            }
        } 
    }//GEN-LAST:event_DangerOptionActionPerformed

    private void DebitMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebitMonthActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Tính năng chưa phát triển","Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_DebitMonthActionPerformed

    private void SalesMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesMonthActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Tính năng chưa phát triển","Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_SalesMonthActionPerformed
    //truy cập thông tin sách
    private void BookInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookInformationActionPerformed
        // TODO add your handling code here:
        new BookInformation().main();
    }//GEN-LAST:event_BookInformationActionPerformed
    //Thông tin NHÀ XUẤT BẢN
    private void BookPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookPublisherActionPerformed
        // TODO add your handling code here:
        new BookPublishers().main();
    }//GEN-LAST:event_BookPublisherActionPerformed
    //Thông tin nhân viên
    private void EmployeeInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeInformationActionPerformed
        // TODO add your handling code here:
        new EmployeeInformation().main();
    }//GEN-LAST:event_EmployeeInformationActionPerformed
    //Lịch sử hoá đơn
    private void BillHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillHistoryActionPerformed
        // TODO add your handling code here:
        new BillHistory().main();
    }//GEN-LAST:event_BillHistoryActionPerformed

    public void main() {
        /* Use FlatLaf theme */
        LookandFeel.setTheme();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminPageForm(username).setVisible(true);           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AboutMenu;
    private javax.swing.JMenuItem BillHistory;
    private javax.swing.JMenuItem BookInformation;
    private javax.swing.JMenu BookInformationMenu;
    private javax.swing.JMenuItem BookPublisher;
    private javax.swing.JMenuItem Changpassword;
    private javax.swing.JMenuItem CustomerInformation;
    public javax.swing.JCheckBoxMenuItem DangerOption;
    private javax.swing.JMenuItem DebitMonth;
    private javax.swing.JMenuItem EmployeeInformation;
    private javax.swing.JMenu EmployeeMenu;
    private javax.swing.JMenuItem ExitApplication;
    private javax.swing.JMenuItem GrantAccount;
    private javax.swing.JMenuItem GroupInformation;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenu MainMenu;
    private javax.swing.JMenuItem RecoveryKey;
    private javax.swing.JMenu ReportMenu;
    private javax.swing.JMenuItem SalesMonth;
    public javax.swing.JMenuItem UserAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
